name: passeio_aumigo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_database: ^10.3.1
  firebase_storage: ^11.3.1
  image_picker: ^1.0.4
  provider: ^6.0.5
  get_it: ^7.6.4
  cloud_firestore: ^4.11.0
  carousel_slider: ^4.0.0
  get: ^4.6.5
  google_fonts: ^4.0.1
  hexcolor: ^3.0.1
  file_picker: ^5.2.5
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  persistent_bottom_nav_bar: ^5.0.2
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
